### ISSUE TITLE
scrollView With custom header Stop

### ISSUE THREAD

**Issue by dimohamdy** [andreamazz/AMScrollingNavbar#130]
![ios simulator screen shot may 22 2015 2 26 10 pm](https://cloud.githubusercontent.com/assets/1476754/7769674/a1cd377a-008e-11e5-958f-7d5ce2ea5953.png)

if you scroll multi time ,the scrolling stopped

**Comment by dimohamdy** [comment]
[self setScrollableViewConstraint:self.headerConstraint withOffset:60];
this line make problem of custom header

**Comment by prsolucoes** [comment]
I have the same problem. All my apps that use custom header stop working. Searching for a decent component.

**Comment by andreamazz** [comment]
Hi @dimohamdy 
I need more informations on how to reproduce the issue, what do you mean by "scroll multi time"?

**Comment by prsolucoes** [comment]
If you scroll up/down many times the problem happen.

**Comment by prsolucoes** [comment]
![img_3599](https://cloud.githubusercontent.com/assets/395096/7777570/94f28b84-009a-11e5-82a0-ba007e1dd398.PNG)

After scrolldown, a blank space happen here. What change? Because everything was working fine.

**Comment by andreamazz** [comment]
Mmmm the only major difference is from this PR
https://github.com/andreamazz/AMScrollingNavbar/commit/41884c9651c2764e8920121159c952fabd147ce8
Try reverting to version 1.3.4 and let me know.

**Comment by andreamazz** [comment]
Nope, it was another fix that broke everything. I'll fix it right away.

**Comment by andreamazz** [comment]
Done, checkout version `1.3.7`

**Comment by prsolucoes** [comment]
The problem was not solved.

You set:
setNeedsLayout

But it dont solve here.

**Comment by andreamazz** [comment]
I can't no longer reproduce the issue with the latest commit, but I can easily if I revert it. Are you sure you are using the latest version?

**Comment by prsolucoes** [comment]
Yes...log from cocoapods:
Installing AMScrollingNavbar 1.3.7 (was HEAD based on 1.3.6)

**Comment by andreamazz** [comment]
That's weird, it's working correctly on the sample project. 
Can you try with previous version so that I can pinpoint when something went wrong?
Something like 1.3.3 or 1.3.4

**Comment by prsolucoes** [comment]
I tried it. When i scroll down, the blank view are showing. But i dont have a custom header.
Im trying cloning your project and make an example to you.

**Comment by prsolucoes** [comment]
I solved the problem:

```objective-c
- (void)viewDidLoad
{
    [super viewDidLoad];    
    [self setUseSuperview:YES];
    ....
}
```

Thanks.

**Comment by andreamazz** [comment]
:+1:

**Comment by prsolucoes** [comment]
Im trying now with the last version. It works on 1.3.4. Do you have skype?

**Comment by andreamazz** [comment]
I do, but here it's 22:00 of long week's friday, so I'm gonna call it a day :sweat_smile: 
If you have more questions feel free to write them here or in the [repo's chat](https://gitter.im/andreamazz/AMScrollingNavbar)
